stages:
  split_data:
    cmd: python src/stages/split.py --config params.yaml
    deps:
    - data/raw
    params:
    - base
    - split
    outs:
    - data/split/characterset.txt
    - data/split/x_train.txt
    - data/split/x_valid.txt
    - data/split/y_train.txt
    - data/split/y_valid.txt
  create_datasets:
    cmd: python src/stages/datasets.py --config params.yaml
    deps:
    - data/split/x_train.txt
    - data/split/x_valid.txt
    - data/split/y_train.txt
    - data/split/y_valid.txt
    params:
    - base
    - transform
    outs:
    - data/datasets/train_dataset
    - data/datasets/validation_dataset
  model_setup:
    cmd: python src/stages/model_setup.py --config params.yaml
    deps:
    - data/split/characterset.txt
    params:
    - base
    - model_setup
    outs:
    - models/untrained_model.h5
  training:
    cmd: python src/stages/training.py --config params.yaml
    deps:
    - data/datasets/train_dataset
    - data/datasets/validation_dataset
    - models/untrained_model.h5
    params:
    - base
    - train
    outs:
    - models/prediction_model.h5
    - models/trained_model.h5
  predict:
    cmd: python src/stages/predict.py --config params.yaml
    deps:
    - data/datasets/validation_dataset
    - data/split/characterset.txt
    - models/prediction_model.h5
