base:
  random_seed: 98723

split:
  train_fraction: 0.9
  shuffle: True
  input: 'data/raw'
  output: 'data/split'


transform:
  image_width: 200
  image_height: 50
  batch_size: 16
  input: 'data/split'
  output: 'data/datasets'
